import { readFileSync, statSync } from 'node:fs'
import { dirname, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { BaseSequencer, type TestSpecification } from 'vitest/node'
import { defineConfig, mergeConfig } from 'vitest/config'
import viteConfig from './vite.config.ts'

/** The repository root: test files are known by their path from here (`tests/frontend/...`). */
const ROOT = dirname(fileURLToPath(import.meta.url))

/** How long each test file took (ms, `mise run test:durations`): what the CI shards are balanced by. */
const DURATIONS = `${ROOT}/tests/frontend/durations.json`

/**
 * Splits the test files over the CI shards (`--shard=N/3`) by how long they take, not by their number (Vitest's own split, which put
 * the heavy files together and made one shard take twice as long as another): longest first, each to the shard with the least so far.
 * A file not measured yet counts by its size (integration tests take about 2.5 ms a byte, unit tests next to nothing). Every shard works
 * the split out alike (ties go by path), so each runs its part and nothing is left out or run twice.
 */
class DurationSequencer extends BaseSequencer {
  override async shard(files: TestSpecification[]): Promise<TestSpecification[]> {
    const { index, count } = this.ctx.config.shard!
    let known: Record<string, number> = {}
    try {
      known = JSON.parse(readFileSync(DURATIONS, 'utf8')) as Record<string, number>
    } catch {
      // Not measured: every file counts by its size.
    }
    const weighed = files
      .map((spec) => {
        const path = relative(ROOT, spec.moduleId).replaceAll('\\', '/')
        return { spec, path, ms: known[path] ?? statSync(spec.moduleId).size * (path.includes('.integration.') ? 2.5 : 0.1) }
      })
      .sort((a, b) => b.ms - a.ms || (a.path < b.path ? -1 : 1))
    const shards = Array.from({ length: count }, () => ({ ms: 0, specs: [] as TestSpecification[] }))
    for (const file of weighed) {
      const lightest = shards.reduce((least, shard) => (shard.ms < least.ms ? shard : least))
      lightest.ms += file.ms
      lightest.specs.push(file.spec)
    }
    return shards[index - 1].specs
  }
}

export default mergeConfig(
  viteConfig,
  defineConfig({
    test: {
      environment: 'jsdom',
      setupFiles: ['../../tests/frontend/support/setup.ts'],
      // A whole test may take longer than Vitest's 5 s default on CI (coverage on, a slower runner): the first test of a file loads
      // the lazy pages, and the photo reading tests wait for real 1.5 s polls. Missing elements still fail after 5 s (setup.ts).
      testTimeout: 15_000,
      include: ['../../tests/frontend/**/*.{unit,integration}.test.{ts,tsx}'],
      sequence: { sequencer: DurationSequencer },
      coverage: {
        provider: 'v8',
        include: ['**/*.{ts,tsx}'],
        // main.tsx only mounts the app; gql/generated.ts is generated by codegen.
        exclude: ['main.tsx', 'gql/generated.ts'],
        reporter: ['text-summary', 'lcov', 'html'],
        reportsDirectory: '../../coverage/frontend',
      },
    },
  }),
)
